version: '3.3'
  
services:
   development:
      image: hbeckeri/js-stratum-proxy
      build:
         context: .
      restart: always
      user: node
      working_dir: /home/node/app
      environment:
         - POOL_ADDRESS=sha256.eu.nicehash.com
         - POOL_PORT=3334
         - MINER_NAME=proxy
         - MINER_ADDRESS=3Js4sXXk9Ca8Y52CezUxuZcDugVx8NtrDT
      ports:
         - 3333:3333
   ethash:
      image: hbeckeri/js-stratum-proxy
      restart: always
      environment:
         - POOL_ADDRESS=daggerhashimoto.usa.nicehash.com
         - POOL_PORT=3353
         - MINER_NAME=proxy
         - MINER_ADDRESS=3Js4sXXk9Ca8Y52CezUxuZcDugVx8NtrDT
      ports:
         - 3334:3333
   equihash:
      image: hbeckeri/js-stratum-proxy
      restart: always
      environment:
         - POOL_ADDRESS=equihash.eu.nicehash.com
         - POOL_PORT=3357
         - MINER_NAME=proxy
         - MINER_ADDRESS=3Js4sXXk9Ca8Y52CezUxuZcDugVx8NtrDT
      ports:
         - 3335:3333
   cryptonightr:
      image: hbeckeri/js-stratum-proxy
      restart: always
      environment:
         - POOL_ADDRESS=cryptonightr.eu.nicehash.com
         - POOL_PORT=3375
         - MINER_NAME=proxy
         - MINER_ADDRESS=3Js4sXXk9Ca8Y52CezUxuZcDugVx8NtrDT
      ports:
         - 3336:3333
