version: '3.3'
  
services:
   node:
      build:
         context: .
      restart: always
      user: node
      working_dir: /home/node/app
      command: "npm start"
      ports:
         - 3333:3333
