version: '3.3'
  
services:
   node:
      image: hbeckeri/js-stratum-proxy
      build:
         context: .
      restart: always
      user: node
      working_dir: /home/node/app
      command: "npm start"
      environment:
         - POOL_ADDRESS=sha256.eu.nicehash.com
         - POOL_PORT=3334
         - MINER_NAME=proxy
         - MINER_ADDRESS=3Js4sXXk9Ca8Y52CezUxuZcDugVx8NtrDT
      ports:
         - 3333:3333
